CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    permissao ENUM('admin', 'user') NOT NULL
);

CREATE TABLE IF NOT EXISTS tblvizu (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    QNTD INT NOT NULL,
    ESTOQUE_MINIMO INT NOT NULL,
    DESCRICAO VARCHAR(200),
    PRECO DECIMAL(10,2),
    FOTO VARCHAR(255),
    CATEGORIA ENUM('eletrica', 'mecanica', 'geral') NOT NULL
);

CREATE TABLE IF NOT EXISTS tblmove (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM VARCHAR(100) NOT NULL,
    QNTD INT NOT NULL,
    ALMOXARIFE VARCHAR(50) NOT NULL,
    TIPO ENUM('entrada', 'saida') NOT NULL,
    FINALIDADE VARCHAR(500) NOT NULL
);

INSERT INTO usuarios (email, senha_hash, permissao)
VALUES ('admin@senai.com', '$2b$12$eteYB07J9eJ4hKOgGqBYTezWVqL7JIep4Kqc9CA5KsHktGVmOZd5y', 'admin');